/*
* karnex.cpp - dubstep growl instrument
*
* <Insert copyright stuff here>
* This file is part of Linux MultiMedia Studio - http://lmms.sourceforge.net
*
* <Insert GNU stuff here>
* 
*/


#include <QtXml/QDomElement>


#include Karnex.h
//<Include other needed .h files>


//TODO: Note Processing


//TODO: Add 2 Oscs
//        OSC1: Sine, Square, Soft Square, Triangle, Moog
//        OSC2: Wavetable generated by mouth code (needs to be converted to c++)


//Mouth code (CONVERT TO C++)
/*
float* generateMouthWave(float wavetableQuality, float mouth)
{
float step = 1.0 / wavetableQuality;
float* wavetable = new float[wavetableQuality];
for (float i = 0f; i < 1.0; i += step)
{
float position = 1 - i;
float ampEnv = (float)(1 / Math.Pow(position, 2));
wavetable[i * wavetableQuality] = -(float)Math.Sin((position * Math.PI * (2 * mouth))) / ampEnv;
delete position, ampEnv;
}
delete step;
return wavetable;
//delete wavetable; (?)
}
*/


//TODO: Add FM (PM?) Mod code


//TODO: Output